### ISSUE TITLE
offline mode not working (+ suspicious network calls from dependencies)

### ISSUE THREAD

**Issue by Kodmod** [cpacker/MemGPT#1144] opened 2024-03-12 20:39 UTC
**Describe the bug**
I'm using MemGPT in local only mode and every time it is run either through the CLI or Python, several network calls are made to Cloudflare and Microsoft servers. The program even occasionally gets blocked or even crashes until I allow these requests to go through. What is the reason for these calls?

**Please describe your setup**
- [x] How did you install memgpt?
  - `pip install pymemgpt`
- [x] Describe your setup
  - MacOS
  - Terminal, Python library

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

Using Ollama backend

**Comment by sarahwooders** [comment] 2024-03-14 21:24
Can you provide more details on the requests you're seeing? MemGPT is not using external servers if you are using local LLMs, however its possible a library we're depending on is.

**Comment by Kodmod** [comment] 2024-03-14 21:59
I'm using [LuLu](https://objective-see.org/products/lulu.html) as a firewall and it notified me of these requests. They usually occur when running MemGPT (like `memgpt run ...`). Around 7 KB and 16 KB of data are uploaded and downloaded respectively, mainly from AWS CloudFront servers. I haven't captured any packets so far.

**Comment by sarahwooders** [comment] 2024-03-18 22:41
Closing since this since it's likely an issue with one of our dependencies, but happy to chat further to isolate the source of the network requests on discord.

**Comment by Kodmod** [comment] 2024-03-19 06:54
I don't think this should be closed until the program can run offline without issues. It currently either hangs for at least 15 minutes or outright crashes.

**Comment by cpacker** [comment] 2024-03-19 19:17
Gotcha @Kodmod we didn't realize there were issues with running offline, just that there were unknown network calls being made by some dependencies. Will look into this and close with a fix or if we are unable to reproduce the offline run issue. Thanks!

**Closed** 2024-09-20 00:05 UTC
