### ISSUE TITLE
Performance decreased severely

### ISSUE THREAD

**Issue by TheOnlyWiseJEDI** [cpacker/MemGPT#331] opened 2023-11-06 19:18 UTC
Using: text-generastion-webui
Model: ehartford_dolphin-2.2-mistral-7b - not quantized
Installed: using pip install -r requirements
OS: Windows 10
Shell: cmd.exe
Python: Python 3.11.3
pymemgpt installed: yes
Hardware: 12th Gen i7 64GB/RAM, RTX3060 12GB RAM
LLM and MemGPT on same system

I have recently reinstalled memgpt so all is fresh and up to date. I have NOT altered any settings in text-generation-webui. This problem existed before and after a reinstall.  

There is a significant performance decrease since a recent update. 'reporter' said he thought it might be the grammar update and that he noticed it also. What used to be a processing time of 4 - 12 seconds has become more often than not,  20+ seconds. Even as much as 39 seconds. 

With the model loaded and memgpt running these results are consistent through the CLI however if I flip to the webui interface and pose the same question the performance time is more than 1/2 faster than when done through memgpt. This was not true last week (presumably prior to whatever update changed things).

**Comment by cpacker** [comment] 2023-11-06 21:05
@TheOnlyWiseJEDI can you try disabling grammar by forcing a specific model?

If you pass `--model airoboros-l2-70b-2.1`, it shouldn't use grammar, so things should be as they were before (unless there's something I'm missing).

**Comment by TheOnlyWiseJEDI** [comment] 2023-11-06 21:10
It is no longer possible to use --model when using memgpt  with 'run'

[image: image.png]
[image: image.png]

**Comment by TheOnlyWiseJEDI** [comment] 2023-11-06 21:12
I tried to include model when creating a new agent - same result

**Comment by TheOnlyWiseJEDI** [comment] 2023-11-06 21:22
it looked like the images didn't get included when I replied from email, not sure if you could see them, I edited and reapplied the images, they should be available now

**Comment by cpacker** [comment] 2023-11-06 22:06
> It is no longer possible to use --model when using memgpt with 'run' ![image](https://github.com/cpacker/MemGPT/assets/123831682/5c338994-1d5d-415c-a442-ac2d90951dc2) ![image](https://github.com/cpacker/MemGPT/assets/123831682/6ea23a2f-604f-4cab-a333-b1a66fbfc6ee)

@vivi @sarahwooders can we do a hotpatch on this?

**Comment by vivi** [comment] 2023-11-06 22:09
@TheOnlyWiseJEDI For now you can run `memgpt run --model airoboros-l2-70b-2.1` and hit 'N' when asked "Would you like to select an existing agent?"

**Comment by vivi** [comment] 2023-11-06 22:26
@TheOnlyWiseJEDI I can't seem to reproduce your bug on 0.1.18a1. Could you run `pip show pymemgpt` and if the version is <0.1.18a1, run `pip install pymemgpt -U --pre`?

**Comment by TheOnlyWiseJEDI** [comment] 2023-11-07 00:06
ok done. I had 0.1.17, now updated. I did this early this morning, was
there another release today?

What should be fixed now in this update?

**Comment by sarahwooders** [comment] 2023-11-07 01:29
If you run `pip install pymemgpt -U --pre`, you should be able to have the `--model` flag without an error, as long as it matches the model of the agent you are resuming. You don't need to specify any additional flags if you're resuming an existing agent.

**Comment by TheOnlyWiseJEDI** [comment] 2023-11-07 01:32
I can't run memgpt at all now, even with just "memgpt run" - take a look at
the other ticket you created

**Comment by cpacker** [comment] 2023-11-07 06:20
Closing this particular issue because it should be resolved in the update that just went live (0.1.18), but @TheOnlyWiseJEDI feel free to reopen if it's still happening or open a new issue if something else is wrong.

**Closed by cpacker** 2023-11-07 06:20 UTC
Labels: local-llm
